# Generated by Django 4.2.6 on 2023-11-01 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='participants',
            new_name='players',
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bilaapp.group'),
            preserve_default=False,
        ),
    ]
