# Generated by Django 4.2.6 on 2023-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilaapp', '0002_rename_participants_group_players_match_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
